CREATE TABLE CATEGORY (
  ID INTEGER IDENTITY PRIMARY KEY,
  TRANSACTION_TYPE VARCHAR(256),
  CATEGORY_NAME VARCHAR(256),
  CATEGORY_LIMIT DECIMAL
)

CREATE TABLE EXPENSE (
  ID INTEGER IDENTITY PRIMARY KEY,
  TRANSACTION_TYPE VARCHAR(256),
  AMOUNT DECIMAL(10,2),
--   CURRENCY VARCHAR(3),
  USER_ID INTEGER,
  TRANSACTION_DATE TIMESTAMP,
  CATEGORY_ID INTEGER,
  CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE INCOME (
  ID INTEGER IDENTITY PRIMARY KEY,
  TRANSACTION_TYPE VARCHAR(256),
  AMOUNT DECIMAL(10,2),
--   CURRENCY VARCHAR(3),
  USER_ID INTEGER,
  TRANSACTION_DATE TIMESTAMP,
  CATEGORY_ID INTEGER,
  CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE BUDGET (
  ID INTEGER IDENTITY PRIMARY KEY,
  BUDGET_TYPE VARCHAR(256),
  AMOUNT DECIMAL(10,2),
  CATEGORY_ID INTEGER NULLABLE,
  CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID),
  CONSTRAINT BUDGET_NAME UNIQUE (BUDGET_TYPE, CATEGORY_ID)

--   CURRENCY VARCHAR(3) NULL
);